In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

df_sales = pd.read_csv('/content/games_sales.csv')

df_sales.isnull().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [2]:
# จัดการข้อมูลประเภทตัวเลข (Numerical Cleaning)
df_sales['User_Score'] = pd.to_numeric(df_sales['User_Score'], errors='coerce')
df_sales['Year_of_Release'] = pd.to_numeric(df_sales['Year_of_Release'], errors='coerce')

# เติมค่าว่างด้วยค่ากลาง (Median) แยกตามแนวเกม (Genre) เพื่อความแม่นยำสูง
df_sales['Critic_Score'] = df_sales['Critic_Score'].fillna(df_sales.groupby('Genre')['Critic_Score'].transform('median'))
df_sales['User_Score'] = df_sales['User_Score'].fillna(df_sales.groupby('Genre')['User_Score'].transform('median'))

# เติมค่าว่างด้วย Mode
df_sales['Year_of_Release'] = df_sales['Year_of_Release'].fillna(df_sales['Year_of_Release'].mode()[0])

# เก็บตกค่าในช่องที่ใช้ ค่ากลาง (Median) แยกตามแนวเกม (Genre) ไม่ได้ ให้ใช้ Med ของคอลัมน์นั้นแทน
df_sales['Critic_Score'] = df_sales['Critic_Score'].fillna(df_sales['Critic_Score'].median())
df_sales['User_Score'] = df_sales['User_Score'].fillna(df_sales['User_Score'].median())

# จัดการข้อมูลประเภทข้อความ (Categorical Cleaning) เติมช่องว่างด้วย 'Unknown' เพื่อสร้างกลุ่มใหม่
cols_to_fix = ['Publisher', 'Developer', 'Rating', 'Genre', 'Platform','Name']
for col in cols_to_fix:
    df_sales[col] = df_sales[col].fillna('Unknown')

# สร้าง Target สำหรับ Classification
def label_success(sales):
    if sales > 10: return 3    # AAA Hit
    if sales > 1:  return 2    # Successful
    if sales > 0.1: return 1   # Mid-range
    return 0                   # Low-sales

df_sales['success_level'] = df_sales['Global_Sales'].apply(label_success)

# 5. Feature Engineering & Encoding
# ใช้ One-Hot Encoding สำหรับ Genre และ Platform เพื่อให้ Neural Network เรียนรู้ได้ดีขึ้น
X = pd.get_dummies(df_sales[['Genre', 'Platform', 'Critic_Score', 'User_Score', 'Year_of_Release']],
                   columns=['Genre', 'Platform'])
y = df_sales['success_level']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

df_sales.isnull().sum()

Name                  0
Platform              0
Year_of_Release       0
Genre                 0
Publisher             0
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score          0
Critic_Count       8582
User_Score            0
User_Count         9129
Developer             0
Rating                0
success_level         0
dtype: int64

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model_nn = Sequential([
    Dense(256, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dense(4, activation='softmax')
])

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

model_nn.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model_nn.fit(
    X_train_scaled, y_train,
    epochs=60,
    batch_size=64,
    validation_split=0.2,
    verbose=1
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.5507 - loss: 0.9441 - val_accuracy: 0.5720 - val_loss: 0.9004
Epoch 2/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5829 - loss: 0.8732 - val_accuracy: 0.5798 - val_loss: 0.8695
Epoch 3/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5935 - loss: 0.8514 - val_accuracy: 0.5880 - val_loss: 0.8598
Epoch 4/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5936 - loss: 0.8401 - val_accuracy: 0.5824 - val_loss: 0.8603
Epoch 5/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5995 - loss: 0.8299 - val_accuracy: 0.5895 - val_loss: 0.8491
Epoch 6/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6033 - loss: 0.8259 - val_accuracy: 0.5847 - val_loss: 0.8461
Epoch 7/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6054 - loss: 0.8194 - val_accuracy: 0.5955 - val_loss: 0.8397
Epoch 8/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6111 - loss: 0.8134 - val_accuracy: 0.5877 - val_loss: 0.8452
Epoch 9/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6110 - loss: 0.8079 - val_accuracy: 0.5862 - val_loss: 0.8463
Epoch 10/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6144 - loss: 0.8081 - val_accuracy: 0.6000 - val_loss: 0.8397
Epoch 11/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6186 - loss: 0.8021 - val_accuracy: 0.5963 - val_loss: 0.8446
Epoch 12/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6191 - loss: 0.8025 - val_accuracy: 0.6011 - val_loss: 0.8393
Epoch 13/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.6160 - loss: 0.7972 - val_accuracy: 0.5963 - val_loss: 0.8336
Epoch 14/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6196 - loss: 0.7948 - val_accuracy: 0.5996 - val_loss: 0.8392
Epoch 15/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6203 - loss: 0.7917 - val_accuracy: 0.5993 - val_loss: 0.8423
Epoch 16/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6243 - loss: 0.7881 - val_accuracy: 0.5914 - val_loss: 0.8481
Epoch 17/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6186 - loss: 0.7877 - val_accuracy: 0.6052 - val_loss: 0.8353
Epoch 18/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6275 - loss: 0.7819 - val_accuracy: 0.5981 - val_loss: 0.8402
Epoch 19/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6230 - loss: 0.7832 - val_accuracy: 0.6000 - val_loss: 0.8365
Epoch 20/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6269 - loss: 0.7758 - val_accuracy: 0.5970 - val_loss: 0.8382
Epoch 21/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6304 - loss: 0.7760 - val_accuracy: 0.5989 - val_loss: 0.8356
Epoch 22/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6283 - loss: 0.7778 - val_accuracy: 0.6022 - val_loss: 0.8387
Epoch 23/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.6301 - loss: 0.7753 - val_accuracy: 0.6004 - val_loss: 0.8416
Epoch 24/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.6324 - loss: 0.7740 - val_accuracy: 0.5993 - val_loss: 0.8403
Epoch 25/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6311 - loss: 0.7730 - val_accuracy: 0.5869 - val_loss: 0.8498
Epoch 26/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6335 - loss: 0.7692 - val_accuracy: 0.6026 - val_loss: 0.8431
Epoch 27/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6310 - loss: 0.7691 - val_accuracy: 0.5996 - val_loss: 0.8397
Epoch 28/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6353 - loss: 0.7673 - val_accuracy: 0.5970 - val_loss: 0.8524
Epoch 29/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6379 - loss: 0.7622 - val_accuracy: 0.6041 - val_loss: 0.8437
Epoch 30/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6407 - loss: 0.7636 - val_accuracy: 0.5985 - val_loss: 0.8461
Epoch 31/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6374 - loss: 0.7599 - val_accuracy: 0.5985 - val_loss: 0.8536
Epoch 32/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6376 - loss: 0.7608 - val_accuracy: 0.5981 - val_loss: 0.8518
Epoch 33/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6415 - loss: 0.7590 - val_accuracy: 0.5996 - val_loss: 0.8483
Epoch 34/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6378 - loss: 0.7581 - val_accuracy: 0.5959 - val_loss: 0.8437
Epoch 35/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6394 - loss: 0.7562 - val_accuracy: 0.5996 - val_loss: 0.8460
Epoch 36/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6398 - loss: 0.7551 - val_accuracy: 0.6045 - val_loss: 0.8480
Epoch 37/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6423 - loss: 0.7471 - val_accuracy: 0.6011 - val_loss: 0.8500
Epoch 38/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6441 - loss: 0.7499 - val_accuracy: 0.6022 - val_loss: 0.8479
Epoch 39/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6457 - loss: 0.7478 - val_accuracy: 0.5978 - val_loss: 0.8538
Epoch 40/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6468 - loss: 0.7474 - val_accuracy: 0.5985 - val_loss: 0.8514
Epoch 41/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6419 - loss: 0.7491 - val_accuracy: 0.6146 - val_loss: 0.8413
Epoch 42/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6450 - loss: 0.7445 - val_accuracy: 0.6067 - val_loss: 0.8549
Epoch 43/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6461 - loss: 0.7459 - val_accuracy: 0.6071 - val_loss: 0.8507
Epoch 44/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6494 - loss: 0.7434 - val_accuracy: 0.6064 - val_loss: 0.8566
Epoch 45/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6448 - loss: 0.7413 - val_accuracy: 0.6049 - val_loss: 0.8590
Epoch 46/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6440 - loss: 0.7449 - val_accuracy: 0.6011 - val_loss: 0.8556
Epoch 47/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6454 - loss: 0.7400 - val_accuracy: 0.6123 - val_loss: 0.8449
Epoch 48/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6555 - loss: 0.7373 - val_accuracy: 0.6075 - val_loss: 0.8471
Epoch 49/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6501 - loss: 0.7383 - val_accuracy: 0.5918 - val_loss: 0.8585
Epoch 50/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6525 - loss: 0.7326 - val_accuracy: 0.6064 - val_loss: 0.8534
Epoch 51/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6519 - loss: 0.7331 - val_accuracy: 0.6082 - val_loss: 0.8591
Epoch 52/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6467 - loss: 0.7362 - val_accuracy: 0.6112 - val_loss: 0.8643
Epoch 53/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6508 - loss: 0.7318 - val_accuracy: 0.6079 - val_loss: 0.8581
Epoch 54/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6549 - loss: 0.7328 - val_accuracy: 0.6022 - val_loss: 0.8615
Epoch 55/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6523 - loss: 0.7248 - val_accuracy: 0.6056 - val_loss: 0.8620
Epoch 56/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6542 - loss: 0.7299 - val_accuracy: 0.5989 - val_loss: 0.8566
Epoch 57/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6533 - loss: 0.7253 - val_accuracy: 0.6079 - val_loss: 0.8593
Epoch 58/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6546 - loss: 0.7248 - val_accuracy: 0.6090 - val_loss: 0.8613
Epoch 59/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6567 - loss: 0.7228 - val_accuracy: 0.6120 - val_loss: 0.8547
Epoch 60/60
168/168 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6589 - loss: 0.7210 - val_accuracy: 0.6004 - val_loss: 0.8569

In [6]:
loss, accuracy = model_nn.evaluate(X_test_scaled, y_test)
print(f"Neural Network Accuracy: {accuracy*100:.2f}%")

105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6026 - loss: 0.8478
Neural Network Accuracy: 60.26%

In [7]:
import joblib
from google.colab import files

model_columns_nn = X.columns.tolist()
joblib.dump(model_columns_nn, 'model_columns_nn.pkl')

joblib.dump(scaler, 'scaler_nn.pkl')
model_nn.save('game_nn_model.h5')

files.download('game_nn_model.h5')
files.download('scaler_nn.pkl')
files.download('model_columns_nn.pkl')

df_sales.to_csv('cleaned_games_sales.csv', index=False)
files.download('cleaned_games_sales.csv')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.